SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE child_traits;
TRUNCATE TABLE mbti_history;
TRUNCATE TABLE traits_change;
TRUNCATE TABLE child;
TRUNCATE TABLE member;
TRUNCATE TABLE rec_book;
TRUNCATE TABLE feedback;
TRUNCATE TABLE book_traits;
TRUNCATE TABLE book;

SET FOREIGN_KEY_CHECKS = 1;